apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "resesok-trip.fullname" }}
spec:
  host: "{{ .Values.virtualService.name }}"
  trafficPolicy:
    loadBalancer:
      simple: LEAST_REQUEST
      warmupDurationSecs: 300s