trigger: none
pool: 'TJP'

steps:
  - checkout: self
    clean: true
    persistCredentials: true
    path: self
  - checkout: git://Tokyo/resesok-otp@resesok-otp2
    path: master

  - task: JavaToolInstaller@0
    displayName: 'Use JDK 11'
    inputs:
      versionSpec: '11'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  # Look on SourceBranch and ensure that we can only merge from release branch
  # Otherwise exit with error code
  - bash: $(Agent.BuildDirectory)/self/docker-build/azure-deploy/release-check.sh
    displayName: 'Validate source branch'
    env:
      SOURCE_BRANCH: $(System.PullRequest.SourceBranch)
      SELF_DIRECTORY: $(Agent.BuildDirectory)/self
      MASTER_DIRECTORY: $(Agent.BuildDirectory)/master
