apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "service.serviceAccountName" . }}-configmap-reader
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "service.serviceAccountName" . }}-service-reader
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["list", "get", "watch"]
  - apiGroups: ["extensions"]
    resources: ["deployments", "replicates"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "service.serviceAccountName" . }}-read-configmaps
subjects:
  - kind: ServiceAccount
    name: {{ include "service.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "service.serviceAccountName" . }}-configmap-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "service.serviceAccountName" . }}-read-services
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "service.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "service.serviceAccountName" . }}-service-reader
  apiGroup: rbac.authorization.k8s.io

