apiVersion: batch/v1
kind: CronJob
metadata:
  name: resesok-otp-restart-job
spec:
  schedule: "0 2 * * *" # Occurrs 02:00 UTC every night, which is 04:00 swedish summer time (GMT+2)
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            aadpodidbinding: {{.Values.azureIdentity.bindingName}}-restart-role
        spec:
          serviceAccountName: {{include "service.serviceAccountName" .}}-restart-account
          restartPolicy: Never
          containers:
            - name: resesok-otp-restart
              image: tjpcrprod.azurecr.io/argo-rollouts-cli:latest
              command:
                - bash
                - -c
              args:
                - until curl --head localhost:15000 ;
                  do echo Waiting for Sidecar ;
                  sleep 1 ;
                  done ;
                  echo Sidecar available ;
                  currentDate=$(TZ="Europe/Stockholm" date +"%s") ;
                  restartDate=$(date -u --date="TZ=\"Europe/Stockholm\" 04:05" +"%s") ;
                  hourToRestart="$(date -u -d "0 $restartDate sec - $currentDate sec" +"%H")h" ;
                  minuteToRestart="$(date -u -d "0 $restartDate sec - $currentDate sec" +"%M")m" ;
                  secondToRestart="$(date -u -d "0 $restartDate sec - $currentDate sec" +"%S")s" ;
                  kubectl argo rollouts restart resesok-otp -i $hourToRestart$minuteToRestart$secondToRestart ;
                  curl -X POST localhost:15020/quitquitquit ;
      backoffLimit: 0

