apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    spring.cloud.kubernetes.config: "true"
data:
  ApplicationInsightsKey: {{ .Values.ApplicationInsightsKey | b64enc }}
  rabbitMqUsername: {{ .Values.rabbitmq.username | b64enc }}
  rabbitMqPassword: {{ .Values.rabbitmq.password | b64enc }}