apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "otp.name" . }}-otp-config
  namespace: {{ .Release.Namespace }}
data:
  otp-config.json: |+
    {
      "otpFeatures": {
        "APIBikeRental": true,
        "APIServerInfo": true,
        "APIGraphInspectorTile": true,
        "APIUpdaterStatus": true,
        "ConsiderPatternsForDirectTransfers": false,
        "DebugClient": true,
        "FloatingBike": true,
        "MinimumTransferTimeIsDefinitive": false,
        "OptimizeTransfers": true,
        "ParallelRouting": true,
        "TransferConstraints": true,

        "ActuatorAPI": false,
        "DataOverlay": false,
        "FaresV2": false,
        "FlexRouting": true,
        "GoogleCloudStorage": false,
        "ReportApi": false,
        "SandboxAPIGeocoder": false,
        "SandboxAPILegacyGraphQLApi": false,
        "SandboxAPIMapboxVectorTilesApi": false,
        "SandboxAPIParkAndRideApi": false,
        "SandboxAPITransmodelApi": true,
        "SandboxAPITravelTime": false,
        "TransferAnalyzer": false,
        "VehicleToStopHeuristics": false,
        "RealtimeResolver": true
      }
    }